version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pipeline
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
volumes:
  db-data:
