name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run tests
        run: |
          cd backend
          npm test
          cd ../frontend
          npm test

      - name: Notify Slack on success
        if: success()
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s)
          RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          payload=$(cat <<EOF
          {
            "text": "✅ CI passed for ${GITHUB_REPOSITORY} on ${GITHUB_REF}\nCommit: ${COMMIT_MSG}\nRun: ${RUN_URL}"
          }
EOF
          )
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"

      - name: Notify Slack on failure
        if: failure()
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s)
          RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          payload=$(cat <<EOF
          {
            "text": "❌ CI failed for ${GITHUB_REPOSITORY} on ${GITHUB_REF}\nCommit: ${COMMIT_MSG}\nRun: ${RUN_URL}"
          }
EOF
          )
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
